#include <iostream>
#include <exception>

int main() {
	throw std::exception();
	return 0;
}